### ISSUE TITLE
@vue/test-utils with jest complains about unexpected token export

### ISSUE THREAD

**Issue by sakinah-github** [nil/v-drag#4]
We're using "@vue/cli-service": "^3.5.1", and we ran this command
npm run test:unit
And got this:
```
FAIL  src/components/public/SubTierHeaders/DragSubTierHeader.spec.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /app/node_modules/v-drag/dist/main.js:5
    function eventListener(a,t,e="add"){a.forEach(a=>{document[`${e}EventListener`](a,t)})}function returnPositionString(a,t,e){return`matrix(${a||"1, 0, 0, 1,"} ${t}, ${e})`}function updatePosition(a,t){window.data.relativeX=window.data.mouseX*a,window.data.relativeY=window.data.mouseY*t,window.data.move.style.transform=returnPositionString(window.data.matrix,window.data.matrixX+window.data.relativeX,window.data.matrixY+window.data.relativeY)}const callPositionUpdate={x(){updatePosition(!0,!1)},y(){updatePosition(!1,!0)},all(){updatePosition(!0,!0)}};function repeatRaf(){callPositionUpdate[window.data.axis](window.data),window.data.posAnimation=requestAnimationFrame(repeatRaf)}function setUpMovement(){window.data.move.classList.add(window.data.class.move),window.data.posAnimation=requestAnimationFrame(repeatRaf),eventListener(["mousemove","touchmove"],setUpMovement,"remove")}function getTransformValue(a,t){let e=Number(window.getComputedStyle(window.data.move)[t].replace

    SyntaxError: Unexpected token export

      2 | import Vuex from 'vuex'
      3 | import BootstrapVue from 'bootstrap-vue'
    > 4 | import vDrag from 'v-drag'
        | ^
      5 | import DragSubTierHeader from '@/components/public/SubTierHeaders/DragSubTierHeader.vue'
      6 |
      7 | const localVue = createLocalVue()

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (src/components/public/SubTierHeaders/DragSubTierHeader.spec.js:4:1)
```

Our codes:
```
<template>
  <b-button
    v-drag
    :style="style"
    @mouseup="updatePositions($event)"
  >
    {{ details.name }}
  </b-button>
</template>

<script>

import SubTierHeader from './SubTierHeader'
import Vue from 'vue'
import vDrag from 'v-drag'
Vue.use(vDrag)

export default {
  name: 'SubTierHeader',
  extends: SubTierHeader,
  computed: {...},
  },
  methods: {...},
}

</style>
```

**Comment by nil** [comment]
Thanks for reporting the error and helping improve v-drag.

I’ve changed the export format in Rollup from `esm` to `umd`. This change should fix the issue. Update v-drag to version **2.1.2** and say if the error is still persistent or has been fixed.
